[package]
name = "ipld_amt"
description = "Sharded IPLD Array implementation."
version = "1.0.0"
license = "MIT OR Apache-2.0"
authors = ["ChainSafe Systems <info@chainsafe.io>"]
edition = "2018"
repository = "https://github.com/ChainSafe/forest"

[dependencies]
cid = { version = "0.7", default-features = false, features = ["serde-codec"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
once_cell = "1.5"
ahash = { version = "0.7", optional = true }
itertools = "0.10"
fvm_shared = { path = "../../shared" }
blockstore = { version = "0.1.0", path = "../../lib/blockstore" }
anyhow = "1.0.51"

[features]
go-interop = ["ahash"]

[dev-dependencies]
criterion = "0.3.1"

[[bench]]
name = "amt_benchmark"
path = "benches/amt_benchmark.rs"
harness = false
