name: Continuous integration

on:
  push:

jobs:
  rustfmt:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        profile: minimal
        override: true
        components: rustfmt
    - name: Check formatting
      run: cargo fmt -- --check
  check-clippy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        profile: minimal
        target: wasm32-unknown-unknown
        override: true
        components: clippy
    # we don't check the lockfile in; this is needed for cache restoration/saving
    - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
      with:
        command: generate-lockfile
    - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641 # v1.3.0
      with:
        # change this to invalidate cache for this job
        key: v0
    # otherwise the include_bytes! macro fails because this file hasn't been generated
    - run: touch examples/fvm/fvm_example_actor.wasm
      shell: bash
    - uses: actions-rs/clippy@9e02862195d5c88dabdda3c1e7fa53a45ed35ec1 # master
      with:
        args: --all --all-targets -- -D warnings
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.3
    - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        target: wasm32-unknown-unknown
        override: true
    # we don't check the lockfile in; this is needed for cache restoration/saving
    - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
      with:
        command: generate-lockfile
    - uses: protocol/cache-go-action@v1
    - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641 # v1.3.0
      with:
        # change this to invalidate cache for this job
        key: v0
    - uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
      with:
        command: install
        args: cbindgen
    - name: Build on wasm32-unknown-unknown
      run: make RUSTFLAGS="-D warnings"
      shell: bash
